// RMAI Showcase — project inventory
window.SHOWCASE_DATA = {
  groups: [
    {
      id: "live",
      label: "Live · custom domain",
      blurb: "In production on RMAI-owned domains. Real users, real data.",
      projects: [
        {
          id: "hansard",
          name: "Hansard",
          subtitle: "Today in the Parliament",
          url: "https://hansard.realmindsai.com.au/",
          repo: "dewoller/hansard",
          repoPrivate: true,
          year: "2026",
          sector: "Civic tech",
          stack: ["Python", "Postgres", "Full-text search", "PDF ingest"],
          status: "live",
          summary: "Search and browse the Victorian parliamentary record. Daily ingest of debates with PDF download, full-text search and model-benchmark output.",
          for: "Researchers, journalists, civic watchers",
          why: "Doctor Dee's longest-running personal data project. Demonstrates ingestion → DB → searchable web UI on a non-trivial public dataset.",
          featured: true,
        },
        {
          id: "tablebuilder",
          name: "Tablebuilder",
          subtitle: "Compliance reporting tables",
          url: "https://realmindsai.github.io/tablebuilder/",
          appUrl: "https://tablebuilder.realmindsai.com.au/",
          repo: "realmindsai/tablebuilder",
          year: "2026",
          sector: "Regtech",
          stack: ["Web app", "Auth-gated", "Public docs"],
          status: "live · auth-gated app",
          summary: "RMAI's compliance/reporting table generator. Productised tool — paying-customer territory. Public docs, gated app.",
          for: "RMAI clients producing structured compliance tables",
          why: "First fully-productised RMAI tool. Public docs at the GH-Pages URL, gated app at the custom domain.",
        },
        {
          id: "haif",
          name: "Hospital Acupuncture",
          subtitle: "HAIF — implementation framework",
          url: "https://hospitalacupuncture.org/",
          repo: "realmindsai/haif-project",
          year: "2026",
          sector: "Integrative medicine",
          stack: ["Static site", "Custom .org domain"],
          status: "live",
          summary: "Static informational site about a framework for implementing acupuncture in hospital settings. Real client deliverable for a published academic.",
          for: "Clinicians, hospital admins, integrative-medicine researchers",
          why: "Real client deliverable for a published academic (Zhen Zheng). Custom .org domain.",
        },
        {
          id: "nillumbio",
          name: "Nillumbio",
          subtitle: "Biodiversity conservation, NE Melbourne",
          url: "https://nillumbio.actionskills.dev/",
          noEmbed: true,
          year: "2026",
          sector: "Conservation",
          stack: ["WordPress", "Wix→WP migration", "ActionSkills hosting"],
          status: "live · pre-cutover",
          summary: "WordPress migration of a community biodiversity group's Wix site. Hosted on ActionSkills WP infra.",
          for: "Nillumbik community, conservation volunteers",
          why: "Demonstrates RMAI's Wix→WordPress migration capability and ActionSkills hosting.",
        },
        {
          id: "imakeheat",
          name: "I Make Heat",
          subtitle: "Pocket bitcrusher PWA",
          url: "http://imakeheat.realmindsai.com.au/",
          repo: "realmindsai/imakeheat-web",
          year: "2026",
          sector: "Audio / creative tools",
          stack: ["PWA", "Web Audio API", "AudioWorklet", "IndexedDB", "Vite", "TypeScript"],
          status: "live",
          summary: "A pocket bitcrusher progressive web app. Render-on-export audio processing with an IndexedDB archive of past sessions. Installable on iOS/Android home screens.",
          for: "Musicians, sound designers, anyone wanting in-pocket lo-fi audio destruction",
          why: "Showcases RMAI delivering polished installable PWAs with non-trivial Web Audio + worklet engineering. Successor to an Android predecessor — full postmortem informed the rewrite.",
        },
        {
          id: "deals",
          name: "Deal Browser",
          subtitle: "Woolworths & Aldi specials",
          url: "https://deals.realmindsai.com.au/",
          year: "2026",
          sector: "Retail / personal",
          stack: ["Scraper", "systemd timer", "Web UI"],
          status: "live",
          summary: "Web UI over a scraping pipeline that grabs Woolworths/Aldi catalogues, categorises items, and surfaces specials.",
          for: "Personal use; demo of scrape → categorise → useful web app",
          why: "End-to-end pipeline demo: ingestion + categorisation + public-facing browser UI on a custom domain.",
        },
      ],
    },
    {
      id: "ghpages",
      label: "Live · github.io",
      blurb: "Public on GitHub Pages. Custom domain not yet wired.",
      projects: [
        {
          id: "northlink",
          name: "NorthLink AI Demo",
          subtitle: "21+ industry mockups for the W22 Summit",
          url: "https://realmindsai.github.io/northlink-ai/",
          repo: "realmindsai/northlink-ai",
          year: "2026",
          sector: "Lead-gen / interactive",
          stack: ["Vanilla HTML/CSS/JS", "Chart.js", "Leaflet", "Epilogue"],
          status: "live",
          summary: "21+ interactive AI mockup demos across 7 industries — construction, food & bev, healthcare/NDIS and more. Visitors pick an industry and see what AI tools could look like in their business.",
          for: "Booth visitors at NorthLink AI Summit, follow-up leads",
          why: "RMAI's flagship interactive lead-gen artifact. Built so the event framing is removable — reusable indefinitely.",
          featured: true,
        },
        {
          id: "ace-eucalypts",
          name: "ACE Guide to Eucalypts",
          subtitle: "Field guide for Melbourne",
          url: "https://realmindsai.github.io/ACE-Guide-to-Eucalypts-Melbourne/",
          repo: "realmindsai/ACE-Guide-to-Eucalypts-Melbourne",
          year: "2026",
          sector: "Botany / education",
          stack: ["Astro", "GitHub Pages", "Netlify Forms"],
          status: "live",
          summary: "Field guide to eucalypt species of Melbourne with walks, identification info and visitor forms. Vicky Shukuroglou's botanical content.",
          for: "Bushwalkers, naturalists, residents identifying trees",
          why: "Content-rich client site. Shows RMAI doing structured-content publishing with embedded walks/forms.",
        },
        {
          id: "justin-lachal",
          name: "Justin Lachal",
          subtitle: "Personal/professional site",
          url: "https://realmindsai.github.io/justin-lachal-website/",
          repo: "realmindsai/justin-lachal-website",
          year: "2026",
          sector: "Personal site",
          stack: ["Astro", "GitHub Pages"],
          status: "live",
          summary: "Personal/professional site featuring a 'decision pill' interaction (decision-aid UX).",
          for: "Justin's professional contacts, prospective clients/employers",
          why: "Demonstrates RMAI delivering individual professional sites end-to-end.",
        },
      ],
    },
    {
      id: "tools",
      label: "Tools & utilities",
      blurb: "Bespoke utility sites — small surface, real usage.",
      projects: [
        {
          id: "arena",
          name: "Arena Demand Scout",
          subtitle: "Childcare-centre demand modelling",
          url: "https://realmindsai.github.io/arena-demand-scout/",
          repo: "realmindsai/arena-demand-scout",
          year: "2026",
          sector: "Property / demographics",
          stack: ["Dashboard", "ABS data"],
          status: "live",
          summary: "Dashboard comparing Arena REIT's childcare-centre portfolio against ABS childcare demand projections.",
          for: "Arena REIT analysts",
          why: "RMAI client deliverable from W33 (Justin Bailey, Arena REIT).",
        },
        {
          id: "just-ask",
          name: "Just Ask Your Computer",
          subtitle: "AI-tools setup guide",
          url: "https://realmindsai.github.io/just-ask-your-computer/",
          repo: "realmindsai/just-ask-your-computer",
          year: "2026",
          sector: "Education",
          stack: ["Static guide"],
          status: "live",
          summary: "AI-tools setup guide for researchers and professionals.",
          for: "Researchers, professionals new to AI tooling",
          why: "Top-of-funnel educational artifact.",
        },
      ],
    },
    {
      id: "academic",
      label: "Teaching · academic",
      blurb: "Course and tutorial sites Dee delivers as an academic.",
      projects: [
        {
          id: "russel-bootstrap",
          name: "Bootstrap Methods",
          subtitle: "Russell's lecture → interactive site",
          url: "https://dewoller.github.io/Russel_bootstrap_Lecture_to_materials_example/",
          repo: "dewoller/Russel_bootstrap_Lecture_to_materials_example",
          year: "2026",
          sector: "RMIT Psychology / stats education",
          stack: ["Vanilla HTML/CSS/JS", "D3.js v7", "ES modules", "Playwright", "GitHub Pages"],
          status: "live",
          summary: "Transforms a single bootstrapping lecture recording into a rich interactive learning site. 11 lecture sections, 13 SVG diagrams, 4 live D3 simulations (CI builder, resampler, skewed-data demo, sample-size explorer) and a 10-question quiz.",
          for: "RMIT Psychology students learning confidence intervals and bootstrap inference",
          why: "Flagship example for the RMIT Psychology AI Training program — shows how AI tooling turns one lecture into a complete interactive learning artefact.",
          featured: true,
        },
        {
          id: "bulsu",
          name: "BulSU Tutorial 2026",
          subtitle: "Bulacan State University",
          url: "https://realmindsai.github.io/bulsu_tutorial_2026/",
          year: "2026",
          sector: "University tutorial",
          stack: ["Static site"],
          status: "live",
          summary: "Course/tutorial site for a 2026 BulSU delivery.",
          for: "BulSU students",
          why: "Academic delivery — RMAI's teaching surface.",
        },
        {
          id: "cse4dbf",
          name: "CSE4DBF",
          subtitle: "Database fundamentals course",
          url: "https://realmindsai.github.io/cse4dbf/",
          year: "2026",
          sector: "University course",
          stack: ["Static site"],
          status: "live",
          summary: "Database fundamentals course material.",
          for: "Students enrolled in CSE4DBF",
          why: "Long-running academic course site.",
        },
        {
          id: "gdg-dslu",
          name: "GDG DSLU Philippines",
          subtitle: "Google Developer Group, De La Salle–Lipa",
          url: "https://realmindsai.github.io/gdg-dslu-philippines/",
          year: "2026",
          sector: "Developer community",
          stack: ["Static site"],
          status: "live",
          summary: "Google Developer Group event site for DSLU Philippines.",
          for: "GDG DSLU community members",
          why: "Community/teaching engagement.",
        },
      ],
    },
  ],
};
